config/routes.rb
Rails.application.routes.draw do
  #--------自作ページルーティング

  get "menus/list",to: "menus#list"

  #--------自作ページルーティング終わり
  resources :menus
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'application#hello'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
class Menu < ApplicationRecord
  def hogeman
    return "hogege"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "マジンガーZ"
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end
  #--------------------------------------------
  #自作ページ
  def list
    @all_menus = Menu.all
    @menu = Menu.new
  end


  #--------------------------------------------
  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: 'Menu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_params
      params.require(:menu).permit(:menu_name, :reference_url, :notes, :cat_nationality, :cat_main_or_side, :tags, :materials, :created, :updated)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yaamo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'site-all', media: 'all' %>
    <%= yield :css %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Mincho" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/menus/_form.html.erb
<%= form_with(model: menu, local: true) do |form| %>
  <% if menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu.errors.count, "error") %> prohibited this menu from being saved:</h2>
      <ul>
        <% menu.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="col-md-1">
      <%= form.label :menu_name, "料理名" %>
    </div>
    <div class="">
      <%= form.text_field :menu_name %>
    </div>
  </div>
  <div class="field">
    <%= form.label :reference_url, "参考URL" %>
    <%= form.text_field :reference_url %>
  </div>

  <div class="field">
    <%= form.label :notes, "備考" %>
    <%= form.text_area :notes %>
  </div>

  <div class="field">
    <%= form.label :cat_nationality, "料理の国籍" %>
    <%= form.number_field :cat_nationality %>
  </div>

  <div class="field">
    <%= form.label :cat_main_or_side, "主菜・副菜" %>
    <%= form.number_field :cat_main_or_side %>
  </div>

  <div class="field">
    <%= form.label :tags, "タグ（カンマ区切り）" %>
    <%= form.text_field :tags %>
  </div>

  <div class="field">
    <%= form.label :materials, "材料（カンマ区切り）" %>
    <%= form.text_field :materials %>
  </div>

  <div class="field">
    <%= form.label :created, "作成日" %>
    <%= form.datetime_select :created %>
  </div>

  <div class="field">
    <%= form.label :updated, "更新日" %>
    <%= form.datetime_select :updated %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'menus' %>
<% end %>
<p id="notice"><%= notice %></p>

<h1>お料理たち</h1>

<div class="table-responsive table_wrap">
  <table class="table table-dark table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>料理名</th>
        <th>参考URL</th>
        <th>備考</th>
        <th>料理の国籍</th>
        <th>主菜・副菜</th>
        <th>タグ（カンマ区切り）</th>
        <th>材料（カンマ区切り）</th>
        <th>作成日</th>
        <th>更新日</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.menu_name %></td>
        <td><%= menu.reference_url %></td>
        <td><%= menu.notes %></td>
        <td><%= menu.cat_nationality %></td>
        <td><%= menu.cat_main_or_side %></td>
        <td><%= menu.tags %></td>
        <td><%= menu.materials %></td>
        <td><%= menu.created %></td>
        <td><%= menu.updated %></td>
        <td><%= link_to 'Show', menu %></td>
        <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
        <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/list.html.erb
<% content_for :css do %>
  <%= stylesheet_link_tag 'menus' %>
<% end %>
<h1 class="sawarabimincho">あやこのお料理手帳</h1>
<%= link_to 'メニュー登録', new_menu_path %>
<section class="list_wrap">
  <% @all_menus.each do |menu| %>
  <div class="menu_wrap">
    <div class="menu_name">
      <%= link_to menu.menu_name, menu %>
      <%=  %>
    </div>
    <div class="image_wrap">
      <img class="menu_img" src="<%= image_path("no_image.png") %>" alt="">
    </div>
    <div class="reference_url">
      <a href="<%= menu.reference_url %>"><%= menu.reference_url %></a>
    </div>
    <div class="categories">
      <div class="nationality">
        <%= menu.cat_nationality %>
      </div>
      <div class="main_or_side">
        <%= menu.cat_main_or_side %>
      </div>
    </div>
    <div class="tags">
      タグ：<%= menu.tags %>
    </div>
    <div class="materials">
      材料：<%= menu.materials %>
    </div>
    <div class="notes">
      備考：<%= menu.notes %>
    </div>
  </div>
  <% end %>
</section>

app/views/menus/new.html.erb
<h1>New Menu</h1>

<%= render 'form', menu: @menu %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menu name:</strong>
  <%= @menu.menu_name %>
</p>

<p>
  <strong>Reference url:</strong>
  <%= @menu.reference_url %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @menu.notes %>
</p>

<p>
  <strong>Cat nationality:</strong>
  <%= @menu.cat_nationality %>
</p>

<p>
  <strong>Cat main or side:</strong>
  <%= @menu.cat_main_or_side %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @menu.tags %>
</p>

<p>
  <strong>Materials:</strong>
  <%= @menu.materials %>
</p>

<p>
  <strong>Created:</strong>
  <%= @menu.created %>
</p>

<p>
  <strong>Updated:</strong>
  <%= @menu.updated %>
</p>

<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>